version: '3.3'
services:
  mongosally:
    image: mongo:3.6
    volumes:
      - ./storage:/data/db

  hermitapp:
    build:
      context: ./hermit
      cache_from:
      - python:3.6-alpine
    image: cherrypy/cherrypy
    volumes:
      - ".:/app"
    command: python ${CHERRYPY_APP:-app.py}
